from .utils import PostRecord
from .disease_ner import get_diease_entities_from_text_slow, get_disease_entities_from_text_fast, get_disease_ners_e2e_dataset
from .icd10_ner import   get_icd10_codes_with_indices_from_text_slow